scan_timeout = 10
add_newline = false
format = "$directory$character"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[git_branch]
disabled = true

[git_status]
disabled = true